addons:
  apt:
    sources:
      - chef-current-xenial
    packages:
      - chefdk

install: echo "skip bundle install"

env:
  - CHEF_LICENSE=accept

branches:
  only:
    - master

services: docker

env:
  matrix:
  - INSTANCE=default-ubuntu-1604
  - INSTANCE=default-ubuntu-1804
  - INSTANCE=default-centos-6
  - INSTANCE=default-centos-7
  - INSTANCE=default-opensuse-leap-42
  - INSTANCE=default-opensuse-leap-15
  - INSTANCE=default-query-centos-6
  - INSTANCE=default-query-centos-7
  - INSTANCE=cacher-client-ubuntu-1604
  - INSTANCE=cacher-client-ubuntu-1804
  - INSTANCE=cacher-client-centos-6
  - INSTANCE=cacher-client-centos-7
  - INSTANCE=cacher-ubuntu-1804

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version

script: KITCHEN_LOCAL_YAML=kitchen.dokken.yml kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - chef exec delivery local all
      env: UNIT_AND_LINT=1
